version: '3.9.5'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  api:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - "elasticsearch"