version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - ${ES_PORT}:${ES_PORT}
    networks:
      - fastapi-es
  web-service:
      build: .
      ports:
        - ${APP_PORT}:${APP_PORT}
      depends_on:
        - elasticsearch
      networks:
        - fastapi-es
networks:
  fastapi-es:
    driver: bridge